### ISSUE TITLE
Why should I include the widget?

### ISSUE THREAD

**Issue by umeboshi2** [fightforthefuture/countdown-widget#6]
I tried to read everything the site had to offer, but I can't figure out what is going on.

"We realize it's a big ask, but this is the kind of bad internet legislation" -- this statement was made on a page that concerns a vote that is to be made by the FCC, which is an administrative body in the executive branch of our government.  It is impossible for the FCC to pass legislation.

I am curious if the neutrality will force me to loose the freedom to charge for my service in an arbirtary manner and force me to treat people equally.  As a citizen of the United States of America, I am assured that I have the right to treat people unequally, based on my motive for eating food, while also being ensured that every person who holds office cannot do the same thing.

I wonder sometimes whether the push for net neutrality is misguided.  I will happily pay and ISP more for my packets to have priority.  We only have a limited amount of bandwidth.  Auctioning the bandwidth seems to be the traditional method of fairness in our common law society.

**Comment by ChrisAntaki** [comment]
Thanks for your feedback.

**Comment by ChrisAntaki** [comment]
> I am curious if the neutrality will force me to loose the freedom to charge for my service in an arbirtary manner and force me to treat people equally.

Are you running an ISP?

**Comment by rubbingalcoholic** [comment]
We were referring to the Thune / Upton proposal, which is legislation introduced by Congress to hamstring the FCC and protect cable monopolies, while throwing a bone to the American people. I agree that this could be more clear in the context.

In this country, we have a rich history of regulating companies that reach monopoly status. This is in order to prevent anticompetitive behavior and serious economic damage in the form of [deadweight loss](http://en.wikipedia.org/wiki/Deadweight_loss). Fortunately, the legal frameworks that were relevant to regulating monopolies in the 1930s are still quite relevant today.

It's hard to say if or how this will affect your service, since you didn't identify your service. I assume your concern was related to FCC Commissioner Ajit Pai's hyperbolic statements about Title II leading to price regulation on ISPs. The sections of law he cited have been applied to mobile carriers for years, and this hasn't led to price regulation. It's possible he was distorting the facts for some ulterior motive.

In any case, we appreciate your feedback and will pass your suggestion about the text along to the team.

**Comment by umeboshi2** [comment]
@ChrisAntaki, I manage wireless access points which are all infra to the State of Mississippi, and should therefore not be subject to FCC regulations for lack of jurisdiction.

FWIW, I remember charging more for access to the newer modems.  If you have 50 modems and there are 10 52k modems and 40 33k modems, how can you truly provide neutrality?  It just seems to make sense to split the services.  Thanks for taking the time to inform me further.  I have not had time to learn much about net neutrality, and the main reason that I opened this issue is that I read through the site and didn't really learn much more.

Honestly, seeing people take the time to make a nifty countdown widget and have people take interest caused me to be curious about what was happening.  I do want to spend more time reading about this.  There is already a problem when the telephone lines and the cable lines compete for a very similar service (the same service if only access is desired) but are differentiated legislatively because the future capabilities of the infrastructure are unknown during the drafting of the legislation.

**Comment by ChrisAntaki** [comment]
@umeboshi2 My understanding is that Net Neutrality relates more to the lack of any obstructions to different sources or types of content. For instance, it'd be OK to offer different service tiers to customers. As long as those customers could use their bandwidth to access any legal source without artificial constraints such as: "Netflix loads at 20% of the speed it could load within your allocated bandwidth, whereas our in-house (ex: Xfinity) video delivery service loads at 100% or more of your allocated bandwidth".

**Comment by ChrisAntaki** [comment]
@umeboshi2 Safeguarding free speech and allowing for a truly competitive marketplace of online services are the two main reasons I'm behind Net Neutrality.

**Comment by rubbingalcoholic** [comment]
@umeboshi2 net neutrality won't prevent ISPs from charging more for faster Internet access to end customers. You'll still be able to pay more and get faster Internet access.

Net neutrality prevents ISPs from creating "fast lanes" and "slow lanes" in the interconnection points between service providers. If you're paying for high speed Internet access, then you should get high speed Internet access. But that isn't what's happening. For example, Comcast and Verizon were recently caught throttling down access speeds to Netflix.com. [One customer was paying Verizon for 75mbit/s download speed, but Verizon throttled his access to Netflix to 0.375mbit/s](http://iamnotaprogrammer.com/Verizon-Fios-Netflix-Vyprvpn.html). When he used a VPN to disguise his traffic to Netflix.com, his speed shot back up to 3mbit/s (the maximum Netflix allows for streaming).

The ISPs [forced Netflix to pay them a ton of money](http://www.businessinsider.com/netflix-blog-on-internet-fast-lanes-2015-1) in order to have Netflix traffic delivered to customers at the high speeds the customers were already paying for.

It's wrong that big ISPs were using their monopoly power to shake down smaller companies for money. But there's a lot more to net neutrality than just Verizon vs. Netflix. If ISPs get to decide which content has priority on the Internet, they could throttle back access to political speech they disagree with. It sounds esoteric, but it's a real concern, especially as corporations exert more power over the political process.

You should check out our home page at www.battleforthenet.com. At the bottom, there's an "Extra Reading" section with more links to some really good information.
